### ISSUE TITLE
Consider generating Microsoft.Toolkit.Mvvm based implementation

### ISSUE THREAD

**Issue by ArwynFr** [thomasclaudiushuber/mvvmgen#15]
`Microsoft.Toolkit.Mvvm` is a Windows Community Toolkit project that provides base classes useful when implementing the MVVM pattern. It provides quality implementations of useful patterns used in MVVM applications, especially `ObservableObject`, `RelayCommand` and `AsyncRelayCommand`. Generating code based on that toolkit would mean less code generated, easier integration of advanced mvvm concepts, and concentrating on code generation.

Link to official documentation: https://docs.microsoft.com/en-us/windows/communitytoolkit/mvvm/introduction

**Comment by thomasclaudiushuber** [comment]
Hi @ArwynFr, thank you for the issue. Also MvvmGen has a `ViewModelBase` class, a `DelegateCommand`, and an `EventAggregator`, so these things are not generated. This means MvvmGen is a full MVVM library. Support for other MVVM frameworks was considered at the beginning, but is not planned, as other frameworks will have their own source generators.

If you want to use the MVVM Toolkit - which is a great choice btw - instead of MvvmGen, you can use their source generators that will make it into the next version. See also this issue here: https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3872

I hope this did answer your question. If not, please re-open this issue. Thank you! 

Thomas

**Comment by ArwynFr** [comment]
Thanks for the hint, didn't knew MVVM toolkit was working on a source generator, I'll eagerly look into both generators and compare them. It's probably not very fair of MVVM Toolkit as it benefits from WCT support which in turn gets promotion from docs.microsoft.com ...
