### ISSUE TITLE
How to use mvvmgen to communicate from viewmodel to view?

### ISSUE THREAD

**Issue by Daimonion1980** [thomasclaudiushuber/mvvmgen#24]
Hello 

I'm pretty new to C#/MVVM and in special with mvvmgen.

From what I learned so far is that the way to communicate from view to viewmodel is done via command functionality.

When there is the need to show something, for example a messagebox, from the viewmodel the internet suggest this to do this with a delegate functionality.

ViewModel:
```csharp
public class SampleViewModel : ViewModelBase
{
	public delegate MessageBoxResult MessageBoxDelegateWithoutContent(string title,string text);
	
	public MessageBoxDelegateWithoutContent MBErrorInitialize {get; set;}
	
	private void SomeMethod()
	{
		this.MBErrorInitialize("MBErrorInitialize_Caption", "MBErrorInitialize_Text");
	}
}
```
View:
```csharp
private void UserControl_Loaded(object sender, RoutedEventArgs e)
{
	SampleViewModel? viewmodel = this.DataContext as SampleViewModel;
	if (viewmodel != null)
	{ 
		viewmodel.MBErrorInitialize = (title, text) =>
		{
			return MessageBox.Show(title, text, MessageBoxButton.OK, MessageBoxImage.Error);
		};
	}
}
```
Not the very best solution because in viewmodel there has to be used view code (MessageBoxResult) but this returntype can be changed to a own one. 

I don't see any suggestion in mvvmgen for this path (ViewModel --> View). 

Is it a good pattern to communicate from viewmodel to view with delegates?
Does mvvmgen define a support method for this communication? 
If not does i make sense to implement one?

Thanks for your work on mvvmgen. I appreciate it a lot!

**Comment by thomasclaudiushuber** [comment]
Hi @Daimonion1980 ,

normally you inject a service into your ViewModel to show a dialog or a MessageBox (which is just another dialog).

So, in your case, you would create something like this:

```
public interface IMessageBoxService
{
    void ShowError(string text, string caption);
}

public class MessageBoxService : IMessageBoxService
{
    public void ShowError(string text, string caption)
    {
        MessageBox.Show(text, caption, MessageBoxButton.OK, MessageBoxImage.Error);
    }
}
```
This means that you can now inject an `IMessageBosService` into the ViewModel and use it there. In a Unit Test, you could pass a different implementation of that interface to the ViewModel that does not show a message box, but sets some flags that you can test.

The ViewModel would look like this with MvvmGen: 

```
[Inject(typeof(IMessageBoxService))]
[ViewModel]
public partial class SampleViewModel
{
    private void SomeMethod()
    {
        this.MessageBoxService.ShowError("MBErrorInitialize_Caption", "MBErrorInitialize_Text");
    }
}
```

When you look at the generated code for this, you find there a constructor and also a MessageBoxService property:

```
partial class SampleViewModel : global::MvvmGen.ViewModels.ViewModelBase
{
    public SampleViewModel(WpfApp2.IMessageBoxService messageBoxService)
    {
        this.MessageBoxService = messageBoxService;
        this.OnInitialize();
    }

    partial void OnInitialize();

    protected WpfApp2.IMessageBoxService MessageBoxService { get; private set; }
}
```

This means, to use the ViewModel, you have to pass an `IMessageBoxService` to the constructor. You can use your `MessageBoxService`  implementation that shows a message box:

```
DataContext = new SampleViewModel(new MessageBoxService());
```

Instead of passing the constructor arguments manually like in the statement above, you could set up dependency injection in your app.

**Comment by Daimonion1980** [comment]
Hello @thomasclaudiushuber.

Thank you very much for your information. I appreciate your clear speaking/writing and with your suggestion i will take a look how to implement this into my project. 

Thanks.

Grüße aus dem Schwarzwald.

**Comment by thomasclaudiushuber** [comment]
Thanks @Daimonion1980. I'll close this issue. If there's anything else or if you can't make progress, feel free to comment on this one or to open another one.

PS: Oh, St. Georgen, just around the corner. :) A few years ago, I was captain of the soccer team of Müllheim, and we used to play in St. Georgen during the season. If you want, you can write the next issue in alemannisch. :-)
