### ISSUE TITLE
ViewModel constructor cannot be overloaded

### ISSUE THREAD

**Issue by Dragnalith** [thomasclaudiushuber/mvvmgen#35]
Hello,

Today it is not possible for your view model to have several constructor signature.
If you try to add to add a custom constructor in your view model source file, you cannot initialize commands:
- You cannot directly call `InitializeCommands()` because the method is not marked as `partial`.
- You cannot call the generated constructor because it is not marked as `partial`.

I wish for at least one of them to be partial so I can call it in my code.

**Comment by thomasclaudiushuber** [comment]
Hi @Dragnalith ,

it is possible to have several constructors. You can just call the InitializeCommands method, as it is a method of the ViewModel class. 

This here is a fully valid ViewModel:

```csharp
[ViewModel]
public partial class MainViewModel
{
  public MainViewModel(string customerParameter)
  {
    this.InitializeCommands();
  }

  public MainViewModel(string customerParameter, int customParameter2)
  {
    this.InitializeCommands();
  }

  [Command]
  public void Save() { }
}
```

You can also call the generated constructor

```
  [ViewModel]
  public partial class MainViewModel
  {
    public MainViewModel(string customerParameter) : this()
    {
     
    }

    [Command]
    public void Save() { }
  }
```

There's no need to mark `InitializeCommands` nor the generated constructor as `partial`, because these members are already in your ViewModel class. The ViewModel class is just split across two files, the one you create, and the one generated. 

Please provide a code example where you have problems, then I can take a look at it. But all the issues you described actually work with MvvmGen.

Hope this helps,
Thomas

**Comment by Dragnalith** [comment]
I have tested again, and you're right it works. I am not sure what I did wrong before

**Comment by thomasclaudiushuber** [comment]
No problem @Dragnalith, that's what I'm here for, to help if something does not work as expected.

Glad that it works now for you.

Thank you for the feedback,
Thomas
