### ISSUE TITLE
Unable to get canexecutemethod change notification from inherited class

### ISSUE THREAD

**Issue by wf-soft** [thomasclaudiushuber/mvvmgen#36]
```
[ViewModel]
public abstract partial class TreeModel
{
        [Property]
        public ColItem? _rootNode;

        [Property]
        public ColItem? _selectedNode;
}

[ViewModel]
public partial class LocalTreeModel : TreeModel
{
       [Command(CanExecuteMethod = nameof(CanEditNode))]
        public void EditNode()
        {

        }

        [CommandInvalidate(nameof(RootNode))]
        [CommandInvalidate(nameof(SelectedNode))]
        public bool CanEditNode() => RootNode is not null && SelectedNode is not null && SelectedNode != RootNode;
}
```

**Comment by wf-soft** [comment]
At present, I can only manually execute notifications for each command
![image](https://user-images.githubusercontent.com/62228539/159875714-e69d4fda-aec7-49e7-b8df-88b5ef8beb72.png)

**Comment by thomasclaudiushuber** [comment]
Thank you @wf-soft, I'll look into this

**Comment by thomasclaudiushuber** [comment]
Hey @wf-soft , I think are only two options
a) Generate the code into the properties of the base class
b) Generate something like you wrote to InvalidateCommands.

I see the issue, and maybe having a general InvalidateCommands method would be the way to go. I'll look into this.

I'll promise that I'll come up with something to support this scenario within the next days. I just have to think about the best way to do it.

**Comment by wf-soft** [comment]
@thomasclaudiushuber Great. Mvvmgen is a very easy-to-use library. Less code allows people to reduce errors and omissions

**Comment by thomasclaudiushuber** [comment]
Thank you for reporting this @wf-soft.

NuGet package version 1.1.5 is available that should fix this for you. 

To support invalidating commands when a property of a ViewModel base class was changed, a new `InvalidateCommands` method was introduced in the generator. Instead of invalidating commands in the setter of a property, they're now invalidated in this generated method. That `InvalidateCommands` method is called now by the `OnPropertyChanged` method of the `ViewModelBase` class. That way the framework does not rely on a property setter anymore, which means invalidating a command for a property that is defined in a base class works now without a problem.

You should be able to get rid of your OnPropertyChanged override with version 1.1.5. 

Please let me know how things are going. I'll close this issue here, but feel free to comment if something is not working as expected.

Thank you,
Thomas

**Comment by thomasclaudiushuber** [comment]
Note that also the _Invalidate Commands_ section in the docs was updated to include the new InvalidateCommands method
https://github.com/thomasclaudiushuber/mvvmgen/blob/main/docs/03_work_with_commands.md#invalidate-commands

From the usage point of view, nothing has changed. Your scenario should now just work.

**Comment by wf-soft** [comment]
@thomasclaudiushuber This is pleasant news
