### ISSUE TITLE
Custom ICommand implementation

### ISSUE THREAD

**Issue by alprinias** [thomasclaudiushuber/mvvmgen#75]
Hi,
I recently discoverd this very well thought tool, which makes life so much easier for the MVVM players.

I wonder if there is a way to have a custom ICommand implementation instead of the default DelegateCommand, let's say a "MyCommand", and have the generator use that instead of the default one.

All the best,
Alex

**Comment by thomasclaudiushuber** [comment]
Hi Alex, I did not look into this yet in more detail, but it's definitely something that could be considered.

**Comment by thomasclaudiushuber** [comment]
Hi @alprinias , because of constructor call not possible without a factory. But with a command factory, it works.

The following will be possible in the next release:

```
using MvvmGen;
using MvvmGen.Commands;

namespace MyCode
{
  public class MyCommand : IDelegateCommand
  {
        private readonly Action<object?> _execute;
        private readonly Func<object?, bool>? _canExecute;

        public MyCommand(Action<object?> execute, Func<object?, bool>? canExecute)
        {
            _execute = execute ?? throw new ArgumentNullException(nameof(execute));
            _canExecute = canExecute;
        }

        public event EventHandler? CanExecuteChanged;
        public void RaiseCanExecuteChanged() => CanExecuteChanged?.Invoke(this, EventArgs.Empty);
        public void Execute(object? parameter) => _execute(parameter);
        public bool CanExecute(object? parameter) => _canExecute == null || _canExecute(parameter);
  }

  public class MyCommandFactory : IDelegateCommandFactory
  {
    public IDelegateCommand CreateCommand(Action<object?> execute, Func<bool,object?> canExecute)
    {
      return new MyCommand(execute, canExecute);
    }
  }

  [ViewModel(CommandFactoryType=typeof(MyCommandFactory))]
  public partial class EmployeeViewModel
  {
    [Command]public void SaveAll() { }
  }
}
```
Will generate this code
```
namespace MyCode
{
    partial class EmployeeViewModel : global::MvvmGen.ViewModels.ViewModelBase
    {
        public EmployeeViewModel()
        {
            this.InitializeCommands();
            this.OnInitialize();
        }

        partial void OnInitialize();

        private void InitializeCommands()
        {
            var commandFactory = new MyCode.MyCommandFactory();
            SaveAllCommand = commandFactory.CreateCommand(_ => SaveAll(), null);
        }

        public IDelegateCommand SaveAllCommand { get; private set; }
    }
}
```

So, all you need to do is to implement `IDelegateCommand` on your custom command and then implement an `IDelegateCommandFactory` that returns your command implementation.

Then you can specify your factory with the `ViewModel` attribute's new `CommandFactoryType` property.

**Comment by alprinias** [comment]
Hi Thomas,

In fact, what I would do is leave the implementation to the consuming project, where I generate the ViewModels. In there I would put my desired DelegateCommand.cs. Implementing the ICommand interface, even a custom ICommand interface relevant to the specific ViewModels project. The generator would then just need to generate the Initialization of the commands e.g. SaveOrderCommand = new **DelegateCommand**(_ => SaveOrder()); Only the name of the DelegateCommand needs to be the same as the one generated.

**Comment by thomasclaudiushuber** [comment]
Hi @alprinias , OK, I understand. The issue with this approach is that:
- you need to ensure that you have the correct constructor in your custom implementation, as the generated code relies on that constructor call..
- you must have a RaiseCanExecuteChanged method in your custom implementation, as the generated code relies on this as well.

Besides this, I wonder what is the reason why you want to use different command implementations in a single ViewModel? What are you doing in these command implementations? Normally the command forwards to the ViewModel, and the logic is in the ViewModel. That's why I don't understand what the reason could be to do this, and I'm happy to learn. :-) 

I'll branch off the current factory based implementation from the main branch and keep it open.

**Comment by alprinias** [comment]
Hi Thomas,
Fair question! Well, I am using Wisej (wisej.com), which is, if I may say so, Winforms for the Web. They have started implementing recently a MVVM approach, and for that they have defined their own ICommand inetrface, not the System.Windows.Input one. With their approach it is very simple to have both a Windows Forms application (running on desktop) and a Wisej application (running in a browser) with minor code changes. If I want to use common Viewmodels for those two UI's, I need to have two DelegateCommands, one implementing the Windows.System.Input.ICommnad interface and one implementing the Wisej.Web.ICommand interface. By the way, the difference between the two is that the CommandArgs for the second one are not an object but a specific type.
So, this is the reason. And thanks for your patience!
Alex

**Comment by thomasclaudiushuber** [comment]
Hi Alex, OK, got it. But in this case it should be fine to set the command type at the ViewModel level and not on every individual command method.

There is now a way to do it:

```
[ViewModel(CommandType=typeof(MyCustomCommand))]
```

The downside of this one to the factory pattern provided above is that you have to ensure that a constructor with the following signature exists in your command implementation. If that's not the case, the generated code might have issues to instantiate your command:

```
 public YourCommand(Action<object?> execute, Func<object?, bool>? canExecute = null)
 {
...
 }
```

Hope this helps. Will be part of the next release
