### ISSUE TITLE
ViewModel Inheritance not working

### ISSUE THREAD

**Issue by Telespaz** [thomasclaudiushuber/mvvmgen#77]
Hi,

the constructor is not generated correctly if i inheritade from a ViewModel with parameter in the constructor. The inherited class is not calling the base class constructor with its parameter.

`[ViewModel]
[Inject(typeof(IPermissionManager), PropertyName = "PermissionManager", PropertyAccessModifier = AccessModifier.Public)]
public partial class ViewModelWithSuggestions
{...}`

Inheritating from ViewModelWithSuggestions:

`[ViewModel]
public partial class PhotoareaPropertyGridViewModel : ViewModelWithSuggestions
{...}`

Will lead to this generated code:

`partial class PhotoareaPropertyGridViewModel
{
    public PhotoareaPropertyGridViewModel()
    {
        this.InitializeCommands();
        this.OnInitialize();
    }
}`

Not compiling with error

![image](https://github.com/thomasclaudiushuber/mvvmgen/assets/139346590/37ba1853-e56b-41a5-90a7-474155efd68f)

**Comment by thomasclaudiushuber** [comment]
Hi @Telespaz , thank you for this issue. I was working on this one at the beginning of MVVMGen, but found many scenarios where I was not able to generate the correct code. That's why it's not there yet. And that's the reason why the ViewModel attribute has a `GenerateConstructor` property that you can set to false, so that you can set up your own constructor.

But I keep this open and if time permits, I'll look into it again to find out what could be done here.

**Comment by Telespaz** [comment]
Hi,
thanks, for the information, maybe you could add this to the documentiation ? Couldn't find it.

**Comment by thomasclaudiushuber** [comment]
Fixed with next release
